<?php
/** Автозагрузка классов модуля. Список явный — так виден его состав. */
\Bitrix\Main\Loader::registerAutoLoadClasses('itb.mcp', [
	'Itb\\Mcp\\AuthError' => 'lib/AuthError.php',
	'Itb\\Mcp\\ToolError' => 'lib/ToolError.php',
	'Itb\\Mcp\\Schema'    => 'lib/Schema.php',
	'Itb\\Mcp\\Tool'      => 'lib/Tool.php',
	'Itb\\Mcp\\Registry'  => 'lib/Registry.php',
	'Itb\\Mcp\\Protocol'  => 'lib/Protocol.php',
	'Itb\\Mcp\\Transport' => 'lib/Transport.php',
	'Itb\\Mcp\\Auth'      => 'lib/Auth.php',
	'Itb\\Mcp\\Token'     => 'lib/Token.php',
	'Itb\\Mcp\\Audit'     => 'lib/Audit.php',
	'Itb\\Mcp\\Rate'      => 'lib/Rate.php',
	'Itb\\Mcp\\Setup'     => 'lib/Setup.php',
	'Itb\\Mcp\\Expose'    => 'lib/Expose.php',
	'Itb\\Mcp\\Api'       => 'lib/Api.php',
	'Itb\\Mcp\\D7'        => 'lib/D7.php',
	'Itb\\Mcp\\Data'      => 'lib/Data.php',
	'Itb\\Mcp\\Catalog'   => 'lib/Catalog.php',
	'Itb\\Mcp\\Orders'    => 'lib/Orders.php',
	'Itb\\Mcp\\Users'     => 'lib/Users.php',
	'Itb\\Mcp\\Path'      => 'lib/Path.php',
	'Itb\\Mcp\\Files'     => 'lib/Files.php',
	'Itb\\Mcp\\Sql'       => 'lib/Sql.php',
	'Itb\\Mcp\\Site'      => 'lib/Site.php',
	'Itb\\Mcp\\Tools'     => 'lib/Tools.php',
	'Itb\\Mcp\\Server'    => 'lib/Server.php',

	'Itb\\Mcp\\Orm\\TokenTable' => 'lib/Orm/TokenTable.php',
	'Itb\\Mcp\\Orm\\LogTable'   => 'lib/Orm/LogTable.php',
	'Itb\\Mcp\\Orm\\RateTable'  => 'lib/Orm/RateTable.php',
]);
