<?php
/** Состав модуля. Список общий для установщика и /mcp/check.php. */
return [
	// Запрет HTTP-доступа к папке модуля: без него из неё отдаются исходники,
	// а шаблон точки входа работает как второй эндпоинт.
	'.htaccess',
	'include.php',
	'options.php',
	'lib/Protocol.php',
	'lib/Transport.php',
	'lib/Schema.php',
	'lib/Tool.php',
	'lib/ToolError.php',
	'lib/AuthError.php',
	'lib/Registry.php',
	'lib/Auth.php',
	'lib/Token.php',
	'lib/Audit.php',
	'lib/Rate.php',
	'lib/Setup.php',
	'lib/Expose.php',
	'lib/Api.php',
	'lib/D7.php',
	'lib/Data.php',
	'lib/Orders.php',
	'lib/Tools.php',
	'lib/Server.php',
	'lib/Orm/TokenTable.php',
	'lib/Orm/LogTable.php',
	'lib/Orm/RateTable.php',
];
